-- ============================================================
-- add_missing_recipes.sql (FIXED - correct column names)
-- ============================================================
USE nutribudget;

INSERT IGNORE INTO recipes (recipe_id, recipe_name, meal_type, prep_time, instructions, ingredients_json)
VALUES
(301,'كشري','غداء',30,'اسلق الأرز والعدس والمكرونة. احضر صلصة الطماطم بالثوم والكمون. ضع طبقات وأضف الدقة.','[{"name":"rice","weight_g":150},{"name":"lentils","weight_g":100},{"name":"pasta","weight_g":80},{"name":"tomato_sauce","weight_g":150},{"name":"onion","weight_g":80},{"name":"vegetable_oil","weight_g":20},{"name":"garlic","weight_g":10},{"name":"cumin","weight_g":5},{"name":"vinegar","weight_g":15}]'),
(302,'برجر','غداء',20,'اعمل كفتة برجر واشويها. حطها في الخبز مع الخضار والصلصة.','[{"name":"minced_beef","weight_g":200},{"name":"burger_bun","weight_g":80},{"name":"onion","weight_g":40},{"name":"tomato","weight_g":50},{"name":"lettuce","weight_g":30},{"name":"mayonnaise","weight_g":20},{"name":"ketchup","weight_g":20},{"name":"salt","weight_g":3},{"name":"black_pepper","weight_g":2}]'),
(303,'بيتزا','عشاء',40,'افرد العجينة. ضع الصلصة والجبن والخضار. اخبز في 200 درجة.','[{"name":"pizza_dough","weight_g":250},{"name":"tomato_sauce","weight_g":100},{"name":"mozzarella","weight_g":150},{"name":"bell_pepper","weight_g":50},{"name":"mushroom","weight_g":50},{"name":"olive_oil","weight_g":15},{"name":"salt","weight_g":3}]'),
(304,'مكرونة بالصلصة','غداء',25,'اسلق المكرونة. احضر صلصة اللحمة بالطماطم والثوم. اخلط.','[{"name":"pasta","weight_g":200},{"name":"minced_beef","weight_g":150},{"name":"tomato_sauce","weight_g":200},{"name":"onion","weight_g":60},{"name":"garlic","weight_g":10},{"name":"olive_oil","weight_g":20},{"name":"salt","weight_g":3},{"name":"black_pepper","weight_g":2}]'),
(305,'فراخ مقلية','غداء',30,'تبّل الفراخ بالتوابل والدقيق والبيض. اقليها في زيت ساخن.','[{"name":"chicken","weight_g":400},{"name":"flour","weight_g":80},{"name":"eggs","weight_g":60},{"name":"vegetable_oil","weight_g":100},{"name":"salt","weight_g":5},{"name":"black_pepper","weight_g":3},{"name":"paprika","weight_g":5},{"name":"cumin","weight_g":3}]'),
(306,'ستيك لحم','عشاء',20,'تبّل الستيك. اشويه على نار عالية دقيقتين لكل وجه.','[{"name":"beef_steak","weight_g":300},{"name":"butter","weight_g":20},{"name":"garlic","weight_g":10},{"name":"salt","weight_g":5},{"name":"black_pepper","weight_g":3},{"name":"olive_oil","weight_g":15}]'),
(307,'سوشي','عشاء',45,'اعمل أرز السوشي بالخل والسكر. ضع السمك والخيار ولف.','[{"name":"rice","weight_g":200},{"name":"salmon","weight_g":100},{"name":"cucumber","weight_g":50},{"name":"vinegar","weight_g":20},{"name":"sugar","weight_g":10},{"name":"salt","weight_g":3}]'),
(308,'تاكو','غداء',25,'اشوي اللحمة بالتوابل. أضف الخضار. املأ الخبز.','[{"name":"minced_beef","weight_g":150},{"name":"bread","weight_g":60},{"name":"tomato","weight_g":60},{"name":"onion","weight_g":40},{"name":"lettuce","weight_g":30},{"name":"cumin","weight_g":5},{"name":"paprika","weight_g":3}]'),
(309,'هوت دوج','فطار',10,'اشوي السجق. حطه في الخبز مع الكاتشب والمسطردة.','[{"name":"beef_sausage","weight_g":100},{"name":"bread","weight_g":80},{"name":"ketchup","weight_g":20},{"name":"mustard","weight_g":10},{"name":"onion","weight_g":30}]'),
(310,'كرواسون','فطار',5,'قدّم الكرواسون مع الزبدة والجبن البيضا والعسل.','[{"name":"butter","weight_g":15},{"name":"white_cheese","weight_g":30},{"name":"honey","weight_g":20},{"name":"bread","weight_g":100}]'),
(311,'بطاطس مقلية','غداء',20,'اقطع البطاطس. اقليها في زيت ساخن. تبّل بالملح.','[{"name":"potato","weight_g":300},{"name":"vegetable_oil","weight_g":80},{"name":"salt","weight_g":5},{"name":"black_pepper","weight_g":2}]'),
(312,'بانيه دجاج','غداء',25,'دق صدر الدجاج. غمسه في الدقيق والبيض والبقسماط. اقليه.','[{"name":"chicken_breast","weight_g":300},{"name":"eggs","weight_g":60},{"name":"breadcrumbs","weight_g":80},{"name":"flour","weight_g":40},{"name":"vegetable_oil","weight_g":80},{"name":"salt","weight_g":5},{"name":"black_pepper","weight_g":2}]'),
(313,'بسبوسة','عشاء',40,'اخلط السميد والسكر والزبادي والزبدة. اخبز. أضف القطر.','[{"name":"flour","weight_g":200},{"name":"sugar","weight_g":100},{"name":"yogurt","weight_g":100},{"name":"butter","weight_g":80},{"name":"vanilla","weight_g":3},{"name":"honey","weight_g":50}]'),
(314,'كنافة','عشاء',50,'فرد الكنافة في صينية. ضع الجبن. اخبز وأضف القطر.','[{"name":"phyllo_dough","weight_g":200},{"name":"white_cheese","weight_g":200},{"name":"butter","weight_g":80},{"name":"sugar","weight_g":100},{"name":"honey","weight_g":30}]'),
(315,'أم علي','عشاء',35,'كسّر الخبز. أضف الحليب والسكر والكريمة والمكسرات. اخبز.','[{"name":"bread","weight_g":150},{"name":"milk","weight_g":400},{"name":"sugar","weight_g":80},{"name":"heavy_cream","weight_g":100},{"name":"nuts","weight_g":50}]'),
(316,'فطير مشلتت','فطار',30,'ارسم الطحين. ضع الزبدة وطوّي مرات. اخبز في فرن ساخن.','[{"name":"flour","weight_g":300},{"name":"butter","weight_g":150},{"name":"eggs","weight_g":60},{"name":"milk","weight_g":100},{"name":"salt","weight_g":3},{"name":"sugar","weight_g":20}]');

SELECT recipe_id, recipe_name FROM recipes WHERE recipe_id >= 301 ORDER BY recipe_id;
